---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/melovera/public_html
    - /bin/rm -rf $DEPLOY_PATH/*
    - /bin/bash -lc "source $HOME/.nvm/nvm.sh && nvm install --lts && corepack enable"
    - /bin/bash -lc "corepack enable && pnpm -v || true"
    - /bin/bash -lc "[ -f pnpm-lock.yaml ] && pnpm i --frozen-lockfile || npm ci"
    - /bin/bash -lc "[ -f pnpm-lock.yaml ] && pnpm build || npm run build"
    - /bin/bash -lc "if [ -d dist ]; then rsync -a --delete dist/ $DEPLOY_PATH/; \
                     elif [ -d build ]; then rsync -a --delete build/ $DEPLOY_PATH/; fi"
